export const LESSONS = [
  {
    id: '1',
    title: 'Introduction to Investing',
    description: 'Why investing matters and how to get started',
    icon: '📈',
    topic: 'introduction to investing in Singapore, why it matters and basic concepts like risk and return',
    xp: 50,
  },
  {
    id: '2',
    title: 'Asset Classes',
    description: 'Stocks, ETFs, bonds and CPF investment options',
    icon: '🏦',
    topic: 'asset classes available to Singapore investors including stocks, ETFs, bonds, fixed deposits and CPF Investment Scheme',
    xp: 50,
  },
  {
    id: '3',
    title: 'Risk & Diversification',
    description: 'Managing risk through smart portfolio allocation',
    icon: '⚖️',
    topic: 'investment risk and diversification strategies for Singapore investors',
    xp: 50,
  },
  {
    id: '4',
    title: 'Dollar-Cost Averaging',
    description: 'How regular investing beats trying to time the market',
    icon: '📅',
    topic: 'dollar-cost averaging strategy and how Singapore investors can apply it using Regular Savings Plans and ETFs',
    xp: 50,
  },
  {
    id: '5',
    title: 'Singapore Investment Products',
    description: 'STI ETF, CPF-IS, SSBs and more',
    icon: '🇸🇬',
    topic: 'Singapore-specific investment products including STI ETF, CPF Investment Scheme, Singapore Savings Bonds and robo-advisors like Syfe and StashAway',
    xp: 50,
  },
];