export const MODULES = [
  {
    id: 'module-1',
    title: 'Money Foundations',
    icon: '🏗️',
    color: '#4F46E5',
    colorLight: '#EEF2FF',
    description: 'Get your basics right before anything else',
    chapters: [
      {
        id: 'chapter-1',
        title: 'Understanding Money & Mindset',
        icon: '🧠',
        description: 'Build the right foundation for your financial journey',
        lessons: [
          {
            id: 'lesson-1-1',
            title: 'What is Financial Literacy?',
            icon: '📖',
            xp: 30,
            duration: '5 min',
            topic: 'financial literacy definition, why it matters for international graduates in Singapore, and the key pillars of financial knowledge including budgeting saving investing and debt management',
            sections: [
              { heading: 'What Financial Literacy Really Means', key: 'definition' },
              { heading: 'Why It Matters More Than Ever', key: 'importance' },
              { heading: 'The Cost of Financial Ignorance', key: 'cost' },
              { heading: 'Your Financial Literacy Journey', key: 'journey' },
            ],
            flashcards: [
              { q: 'What is financial literacy?', ragQuery: 'financial literacy definition knowledge skills confidence informed decisions budgeting saving investing' },
              { q: 'Name 3 pillars of financial literacy', ragQuery: 'pillars of financial literacy budgeting saving investing debt management key components' },
              { q: 'What is compound interest and how does it work?', ragQuery: 'compound interest definition how it works example growth over time' },
              { q: 'Why do international students in Singapore face unique financial challenges?', ragQuery: 'international students Singapore financial challenges CPF banking unfamiliar systems' },
              { q: 'What is the Big Three financial literacy test?', ragQuery: 'Big Three financial literacy questions compound interest inflation risk diversification Lusardi' },
            ],
          },
          {
            id: 'lesson-1-2',
            title: 'Common Money Mistakes Graduates Make',
            icon: '⚠️',
            xp: 30,
            duration: '5 min',
            topic: 'common financial mistakes made by fresh graduates in Singapore including lifestyle inflation overspending on credit cards neglecting emergency funds and failing to start investing early',
            sections: [
              { heading: 'Lifestyle Inflation — The Silent Wealth Killer', key: 'lifestyle_inflation' },
              { heading: 'Credit Card Traps to Avoid', key: 'credit_cards' },
              { heading: 'The Emergency Fund Gap', key: 'emergency_fund' },
              { heading: 'Waiting Too Long to Invest', key: 'investing_late' },
            ],
            flashcards: [
              { q: 'What is lifestyle inflation?', ragQuery: 'lifestyle inflation definition spending increases with income wealth trap fresh graduates' },
              { q: 'What is the minimum credit card payment trap?', ragQuery: 'credit card minimum payment interest rate trap Singapore annual percentage rate' },
              { q: 'How much should an emergency fund cover?', ragQuery: 'emergency fund size months expenses Singapore recommended amount' },
              { q: 'What is the cost of waiting 5 years to start investing?', ragQuery: 'cost of delaying investing 5 years compound growth opportunity cost Singapore' },
              { q: 'What is FOMO investing and why is it dangerous?', ragQuery: 'FOMO investing fear of missing out impulsive decisions cryptocurrency meme stocks risk' },
            ],
          },
          {
            id: 'lesson-1-3',
            title: 'Building a Healthy Money Mindset',
            icon: '💪',
            xp: 30,
            duration: '5 min',
            topic: 'building a positive money mindset for young adults in Singapore including paying yourself first delayed gratification financial goal setting and developing positive money habits',
            sections: [
              { heading: 'The Psychology of Money', key: 'psychology' },
              { heading: 'Pay Yourself First', key: 'pay_yourself' },
              { heading: 'Setting SMART Financial Goals', key: 'goals' },
              { heading: 'Building Habits That Stick', key: 'habits' },
            ],
            flashcards: [
              { q: 'What does pay yourself first mean?', ragQuery: 'pay yourself first automatic savings transfer salary financial habit' },
              { q: 'What is a SMART financial goal?', ragQuery: 'SMART financial goal specific measurable achievable relevant time-bound example savings' },
              { q: 'What is delayed gratification in personal finance?', ragQuery: 'delayed gratification resisting spending now for greater financial reward later savings habit' },
              { q: 'What are the 3 buckets of a healthy money mindset?', ragQuery: 'healthy money mindset awareness intentionality consistency financial behaviour' },
              { q: 'What is a net worth statement?', ragQuery: 'net worth statement assets minus liabilities personal finance tracking wealth' },
            ],
          },
        ],
      },
      {
        id: 'chapter-2',
        title: 'Budgeting',
        icon: '📊',
        description: 'Take control of where your money goes every month',
        lessons: [
          {
            id: 'lesson-2-1',
            title: 'The 50/30/20 Rule',
            icon: '📐',
            xp: 30,
            duration: '5 min',
            topic: 'the 50/30/20 budgeting rule applied to Singapore fresh graduates including needs wants and savings categories with Singapore cost of living examples',
            sections: [
              { heading: 'What is the 50/30/20 Rule?', key: 'rule' },
              { heading: 'Needs vs Wants — The Singapore Context', key: 'needs_wants' },
              { heading: 'Applying It on a Fresh Grad Salary', key: 'application' },
              { heading: 'When 50/30/20 Needs Adjusting', key: 'adjustments' },
            ],
            flashcards: [
              { q: 'What are the three buckets in the 50/30/20 rule?', ragQuery: '50 30 20 budgeting rule needs wants savings debt repayment categories explanation' },
              { q: 'How much should a fresh grad in Singapore save monthly on a typical salary?', ragQuery: 'fresh graduate Singapore salary savings target monthly amount 20 percent' },
              { q: 'Is public transport a Need or Want in Singapore?', ragQuery: 'Singapore public transport MRT bus necessity need monthly cost commuting' },
              { q: 'When should you adjust the 50/30/20 rule?', ragQuery: 'adjust 50 30 20 budget high debt high rent Singapore modification' },
              { q: 'What is zero-based budgeting?', ragQuery: 'zero based budgeting every dollar assigned income minus expenses equals zero method' },
            ],
          },
          {
            id: 'lesson-2-2',
            title: 'Budgeting on a Singapore Salary',
            icon: '🇸🇬',
            xp: 30,
            duration: '6 min',
            topic: 'budgeting for fresh graduates in Singapore with typical salary ranges, HDB rental costs, food expenses at hawker centres and restaurants, transport costs',
            sections: [
              { heading: 'Typical Fresh Grad Salaries in Singapore', key: 'salaries' },
              { heading: 'Breaking Down Singapore\'s Cost of Living', key: 'cost_of_living' },
              { heading: 'A Sample Monthly Budget', key: 'sample_budget' },
              { heading: 'Cutting Costs Without Sacrificing Quality of Life', key: 'cutting_costs' },
            ],
            flashcards: [
              { q: 'What is the median fresh graduate starting salary in Singapore?', ragQuery: 'median fresh graduate starting salary Singapore university 2024 monthly income' },
              { q: 'What does a typical HDB room rental cost in Singapore?', ragQuery: 'HDB room rental cost Singapore monthly price range location' },
              { q: 'How much does eating at a hawker centre cost vs a restaurant?', ragQuery: 'hawker centre meal cost Singapore versus restaurant dining price comparison' },
              { q: 'What is the typical monthly transport cost in Singapore?', ragQuery: 'Singapore monthly MRT bus transport cost average commuter SimplyGo' },
              { q: 'Name 3 ways to reduce daily expenses in Singapore', ragQuery: 'reduce expenses Singapore hawker centres public transport budget supermarket FairPrice' },
            ],
          },
          {
            id: 'lesson-2-3',
            title: 'Expense Tracking Methods',
            icon: '📱',
            xp: 30,
            duration: '5 min',
            topic: 'expense tracking methods for Singapore residents including budgeting apps, spreadsheet tracking, bank categorisation tools like DBS NAV Planner',
            sections: [
              { heading: 'Why Tracking is Non-Negotiable', key: 'why_track' },
              { heading: 'Digital Tools Available in Singapore', key: 'digital_tools' },
              { heading: 'The Spreadsheet Method', key: 'spreadsheet' },
              { heading: 'Building a Tracking Habit', key: 'habit' },
            ],
            flashcards: [
              { q: 'What is the DBS NAV Planner?', ragQuery: 'DBS NAV Planner budgeting tool transaction categorisation spending tracker app' },
              { q: 'Name 3 popular expense tracking apps in Singapore', ragQuery: 'expense tracking apps Singapore Seedly Money Manager YNAB budgeting tools' },
              { q: 'What is the envelope budgeting method?', ragQuery: 'envelope budgeting method cash categories spending limit digital physical' },
              { q: 'How often should you review your budget?', ragQuery: 'budget review frequency weekly monthly quarterly financial habit best practice' },
              { q: 'What is Seedly and what makes it useful for Singapore users?', ragQuery: 'Seedly Singapore personal finance app bank account aggregation spending categories community' },
            ],
          },
        ],
      },
      {
        id: 'chapter-3',
        title: 'Saving & Emergency Funds',
        icon: '🏦',
        description: 'Build your financial safety net before investing',
        lessons: [
          {
            id: 'lesson-3-1',
            title: 'Why Your Savings Rate Matters',
            icon: '💰',
            xp: 30,
            duration: '5 min',
            topic: 'savings rate importance for wealth building, how savings rate matters more than income, Singapore savings culture',
            sections: [
              { heading: 'Savings Rate vs Income — What Matters More?', key: 'savings_rate' },
              { heading: 'Singapore\'s High Cost of Living Challenge', key: 'cost_challenge' },
              { heading: 'How to Increase Your Savings Rate', key: 'increase_rate' },
              { heading: 'Automating Your Savings', key: 'automate' },
            ],
            flashcards: [
              { q: 'What is a savings rate and why does it matter?', ragQuery: 'savings rate definition percentage income saved wealth building importance' },
              { q: 'Which matters more — high income or high savings rate?', ragQuery: 'savings rate versus high income wealth accumulation comparison financial independence' },
              { q: 'What is an automatic savings transfer and how do you set one up?', ragQuery: 'automatic savings transfer GIRO standing instruction Singapore bank payday' },
              { q: 'What is Singapore\'s national savings rate?', ragQuery: 'Singapore national savings rate GDP percentage CPF mandatory contributions' },
              { q: 'What is the difference between gross and net savings rate?', ragQuery: 'gross net savings rate CPF contributions take home pay Singapore difference' },
            ],
          },
          {
            id: 'lesson-3-2',
            title: 'Building Your Emergency Fund',
            icon: '🛡️',
            xp: 30,
            duration: '5 min',
            topic: 'building an emergency fund in Singapore, how much to save, where to keep it',
            sections: [
              { heading: 'What Counts as an Emergency?', key: 'what_counts' },
              { heading: 'How Much Do You Actually Need?', key: 'how_much' },
              { heading: 'Where to Keep Your Emergency Fund in Singapore', key: 'where_to_keep' },
              { heading: 'Building It Fast on a Tight Budget', key: 'build_fast' },
            ],
            flashcards: [
              { q: 'What qualifies as a financial emergency?', ragQuery: 'financial emergency definition job loss medical bills urgent repairs genuine emergency fund use' },
              { q: 'How many months of expenses should an emergency fund cover?', ragQuery: 'emergency fund months expenses recommended 3 6 months coverage Singapore' },
              { q: 'How much does a Singapore grad need in an emergency fund?', ragQuery: 'Singapore graduate emergency fund target amount monthly expenses cost of living' },
              { q: 'Should an emergency fund be invested in stocks?', ragQuery: 'emergency fund invested stocks liquid accessible savings account not invested' },
              { q: 'Which Singapore account is ideal for an emergency fund?', ragQuery: 'Singapore savings account emergency fund high yield liquid accessible OCBC DBS UOB' },
            ],
          },
          {
            id: 'lesson-3-3',
            title: 'Saving Goals & Sinking Funds',
            icon: '🎯',
            xp: 30,
            duration: '5 min',
            topic: 'sinking funds and savings goals for Singapore graduates including holiday funds, laptop replacement, home renovation',
            sections: [
              { heading: 'What is a Sinking Fund?', key: 'sinking_fund' },
              { heading: 'Common Savings Goals for Singapore Grads', key: 'common_goals' },
              { heading: 'Setting Up Multiple Savings Buckets', key: 'buckets' },
              { heading: 'Savings Goal Timelines', key: 'timelines' },
            ],
            flashcards: [
              { q: 'What is a sinking fund?', ragQuery: 'sinking fund definition dedicated savings future planned expense monthly contribution' },
              { q: 'Name 4 common sinking funds for Singapore graduates', ragQuery: 'common savings goals Singapore graduates holiday laptop rental deposit professional development' },
              { q: 'How do you calculate a monthly sinking fund contribution?', ragQuery: 'sinking fund calculation target amount divided by months formula example' },
              { q: 'What is the difference between an emergency fund and a sinking fund?', ragQuery: 'emergency fund versus sinking fund difference unexpected planned expenses' },
              { q: 'Which Singapore banks support multiple savings goals?', ragQuery: 'Singapore bank multiple savings goals buckets DBS OCBC goal based savings feature' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'module-2',
    title: 'Banking & Cash Management',
    icon: '🏦',
    color: '#0891B2',
    colorLight: '#ECFEFF',
    description: 'Make your money work before you even invest',
    chapters: [
      {
        id: 'chapter-4',
        title: 'Singapore Banking Landscape',
        icon: '🏙️',
        description: 'Navigate Singapore\'s banks like a local',
        lessons: [
          {
            id: 'lesson-4-1',
            title: 'The Big Three Banks',
            icon: '🏛️',
            xp: 30,
            duration: '5 min',
            topic: 'Singapore Big Three banks DBS OCBC UOB comparison for fresh graduates and international students',
            sections: [
              { heading: 'DBS — Singapore\'s Largest Bank', key: 'dbs' },
              { heading: 'OCBC — The Relationship Bank', key: 'ocbc' },
              { heading: 'UOB — The Rewards King', key: 'uob' },
              { heading: 'Which Bank Should You Choose?', key: 'which_bank' },
            ],
            flashcards: [
              { q: 'What is DBS Multiplier and how does it work?', ragQuery: 'DBS Multiplier account interest rate conditions salary credit transactions bonus interest' },
              { q: 'What makes OCBC 360 account attractive?', ragQuery: 'OCBC 360 account bonus interest conditions salary save spend insurance' },
              { q: 'What is UOB One account known for?', ragQuery: 'UOB One account interest rate salary credit card spend conditions bonus' },
              { q: 'Can international students open a bank account in Singapore?', ragQuery: 'international students open bank account Singapore requirements passport student pass' },
              { q: 'What is a multi-currency account and who offers it in Singapore?', ragQuery: 'multi-currency account Singapore Wise YouTrip international transfers foreign currency' },
            ],
          },
          {
            id: 'lesson-4-2',
            title: 'Digital Banks in Singapore',
            icon: '📱',
            xp: 30,
            duration: '5 min',
            topic: 'digital banks in Singapore including GXS Bank and Maribank features and comparison to traditional banks',
            sections: [
              { heading: 'What Are Digital Banks?', key: 'digital_banks' },
              { heading: 'GXS Bank — Grab\'s Bank', key: 'gxs' },
              { heading: 'Maribank — Sea\'s Bank', key: 'maribank' },
              { heading: 'Digital vs Traditional — Which to Use?', key: 'comparison' },
            ],
            flashcards: [
              { q: 'What is a digital bank and how does it differ from traditional banks?', ragQuery: 'digital bank definition no physical branches online only lower fees higher interest rates Singapore' },
              { q: 'What is GXS Bank and who owns it?', ragQuery: 'GXS Bank Singapore Grab Singtel digital bank features savings interest rate' },
              { q: 'What is Maribank and who is it connected to?', ragQuery: 'Maribank Singapore Sea Group Shopee digital bank features interest rate' },
              { q: 'Are digital banks in Singapore safe and regulated?', ragQuery: 'digital banks Singapore MAS licensed regulated safe SDIC deposit insurance' },
              { q: 'What is SDIC and what does it cover?', ragQuery: 'SDIC Singapore Deposit Insurance Corporation coverage limit per depositor per bank' },
            ],
          },
          {
            id: 'lesson-4-3',
            title: 'Smart Account Management',
            icon: '⚙️',
            xp: 30,
            duration: '5 min',
            topic: 'smart bank account management in Singapore including PayNow, GIRO, avoiding fees, and multi-account strategy',
            sections: [
              { heading: 'Setting Up PayNow & PayLah', key: 'paynow' },
              { heading: 'GIRO — Automating Your Finances', key: 'giro' },
              { heading: 'Avoiding Common Bank Fees', key: 'fees' },
              { heading: 'The Multi-Account Strategy', key: 'multi_account' },
            ],
            flashcards: [
              { q: 'What is PayNow and how does it work?', ragQuery: 'PayNow Singapore instant fund transfer NRIC FIN mobile number free interbank' },
              { q: 'What is GIRO and what is it used for?', ragQuery: 'GIRO Singapore automatic deduction recurring payments bills insurance premiums' },
              { q: 'What is the typical fall-below fee for Singapore bank accounts?', ragQuery: 'fall below fee Singapore bank accounts minimum balance monthly charge avoid' },
              { q: 'What is the multi-account strategy for Singapore savers?', ragQuery: 'multiple bank accounts strategy Singapore salary emergency sinking fund separate purpose' },
              { q: 'What is DBS PayLah and what can it do?', ragQuery: 'DBS PayLah mobile wallet peer transfer QR payment Singapore features' },
            ],
          },
        ],
      },
      {
        id: 'chapter-5',
        title: 'High Yield Savings Accounts',
        icon: '📈',
        description: 'Earn more interest with zero extra risk',
        lessons: [
          {
            id: 'lesson-5-1',
            title: 'How HYSAs Work',
            icon: '💡',
            xp: 30,
            duration: '5 min',
            topic: 'how high yield savings accounts work in Singapore, bonus interest conditions, and how to evaluate HYSAs',
            sections: [
              { heading: 'Base vs Bonus Interest Explained', key: 'base_bonus' },
              { heading: 'Common Conditions to Unlock Bonus Interest', key: 'conditions' },
              { heading: 'How to Read a HYSA Rate Table', key: 'rate_table' },
              { heading: 'Is the Effort Worth It?', key: 'effort' },
            ],
            flashcards: [
              { q: 'What is the base interest rate on most Singapore savings accounts?', ragQuery: 'base interest rate Singapore savings account standard rate before bonus conditions' },
              { q: 'What are the most common HYSA conditions in Singapore?', ragQuery: 'HYSA conditions Singapore salary crediting credit card spend insurance investment bonus interest' },
              { q: 'What does tiered interest mean in a savings account?', ragQuery: 'tiered interest rate savings account different rates balance levels Singapore explanation' },
              { q: 'Can you lose money in a high yield savings account?', ragQuery: 'HYSA risk lose money principal protected SDIC insured Singapore savings account safe' },
              { q: 'What is the effective interest rate on a HYSA?', ragQuery: 'effective interest rate HYSA Singapore calculate actual rate earned conditions tiers' },
            ],
          },
          {
            id: 'lesson-5-2',
            title: 'DBS Multiplier vs OCBC 360 vs UOB One',
            icon: '⚖️',
            xp: 30,
            duration: '7 min',
            topic: 'detailed comparison of DBS Multiplier, OCBC 360, and UOB One savings accounts in Singapore',
            sections: [
              { heading: 'DBS Multiplier — Deep Dive', key: 'dbs_multiplier' },
              { heading: 'OCBC 360 — Deep Dive', key: 'ocbc_360' },
              { heading: 'UOB One — Deep Dive', key: 'uob_one' },
              { heading: 'Head-to-Head: Which Wins for Fresh Grads?', key: 'comparison' },
            ],
            flashcards: [
              { q: 'What is the current maximum interest rate on DBS Multiplier?', ragQuery: 'DBS Multiplier maximum interest rate current 2024 conditions categories salary' },
              { q: 'What is the OCBC 360 Save bonus condition?', ragQuery: 'OCBC 360 Save bonus condition increase balance monthly amount interest' },
              { q: 'What monthly spend unlocks UOB One bonus interest?', ragQuery: 'UOB One monthly credit card spend requirement bonus interest rate unlock conditions' },
              { q: 'Which HYSA is easiest for fresh grads with no credit card?', ragQuery: 'easiest HYSA fresh graduates Singapore no credit card salary crediting only interest' },
              { q: 'What happens to HYSA interest if you miss a condition one month?', ragQuery: 'HYSA miss condition monthly bonus interest reset base rate Singapore account' },
            ],
          },
          {
            id: 'lesson-5-3',
            title: 'Maximising Your Interest',
            icon: '🚀',
            xp: 30,
            duration: '5 min',
            topic: 'strategies to maximise HYSA interest in Singapore including account stacking and combining with SSBs',
            sections: [
              { heading: 'The Account Stacking Strategy', key: 'stacking' },
              { heading: 'Meeting Conditions Without Overspending', key: 'conditions' },
              { heading: 'Combining HYSAs with SSBs', key: 'combining' },
              { heading: 'A Sample Optimised Cash Strategy', key: 'sample' },
            ],
            flashcards: [
              { q: 'What is the account stacking strategy for Singapore savers?', ragQuery: 'account stacking multiple savings accounts Singapore HYSA SSB fixed deposit strategy' },
              { q: 'How do you meet the credit card spend condition without overspending?', ragQuery: 'meet credit card spend condition HYSA bills subscriptions groceries pay full monthly' },
              { q: 'When should you move savings from a HYSA to SSBs?', ragQuery: 'move savings HYSA SSB Singapore when emergency fund funded medium term savings' },
              { q: 'What is a cash management account in Singapore?', ragQuery: 'cash management account Singapore Syfe Cash StashAway Simple money market fund liquidity return' },
              { q: 'What is the SDIC insurance limit and how does it affect account strategy?', ragQuery: 'SDIC insurance limit per bank Singapore spread deposits multiple banks protection' },
            ],
          },
        ],
      },
      {
        id: 'chapter-6',
        title: 'Singapore Savings Bonds & Fixed Deposits',
        icon: '🏛️',
        description: 'Safe, government-backed ways to grow your cash',
        lessons: [
          {
            id: 'lesson-6-1',
            title: 'Singapore Savings Bonds Explained',
            icon: '🇸🇬',
            xp: 30,
            duration: '6 min',
            topic: 'Singapore Savings Bonds SSB explained including how to buy, interest rates, step-up feature, and redemption',
            sections: [
              { heading: 'What Are Singapore Savings Bonds?', key: 'what_are_ssb' },
              { heading: 'The Step-Up Interest Feature', key: 'step_up' },
              { heading: 'How to Buy and Redeem SSBs', key: 'how_to_buy' },
              { heading: 'Are SSBs Right for You?', key: 'suitability' },
            ],
            flashcards: [
              { q: 'What are Singapore Savings Bonds?', ragQuery: 'Singapore Savings Bonds SSB government backed capital guaranteed flexible redemption MAS' },
              { q: 'What is the SSB step-up interest feature?', ragQuery: 'SSB step up interest feature rates increase each year hold longer SGS rates' },
              { q: 'How do you buy Singapore Savings Bonds?', ragQuery: 'how to buy Singapore Savings Bonds internet banking ATM DBS OCBC UOB minimum amount' },
              { q: 'When and how can you redeem SSBs?', ragQuery: 'redeem Singapore Savings Bonds any month notice period business days penalty' },
              { q: 'What is the individual SSB holding limit?', ragQuery: 'Singapore Savings Bonds individual holding limit maximum amount per person' },
            ],
          },
          {
            id: 'lesson-6-2',
            title: 'T-Bills & Fixed Deposits',
            icon: '📄',
            xp: 30,
            duration: '5 min',
            topic: 'Singapore Treasury bills T-bills and fixed deposits comparison and when to use each',
            sections: [
              { heading: 'What Are T-Bills?', key: 'tbills' },
              { heading: 'How T-Bill Auctions Work', key: 'auctions' },
              { heading: 'Fixed Deposits — The Simple Alternative', key: 'fixed_deposits' },
              { heading: 'T-Bills vs FDs vs SSBs — When to Use Each', key: 'comparison' },
            ],
            flashcards: [
              { q: 'What are Singapore T-bills?', ragQuery: 'Singapore T-bills treasury bills 6 month 1 year maturity discount government securities yield' },
              { q: 'How do you buy Singapore T-bills?', ragQuery: 'buy Singapore T-bills internet banking ATM auction apply DBS OCBC UOB retail' },
              { q: 'What is a competitive vs non-competitive T-bill bid?', ragQuery: 'competitive non-competitive T-bill bid cut-off yield retail investor recommendation Singapore' },
              { q: 'What is a fixed deposit and how does it work?', ragQuery: 'fixed deposit Singapore bank guaranteed interest rate fixed period early withdrawal penalty' },
              { q: 'When should you choose fixed deposits over SSBs?', ragQuery: 'fixed deposit versus SSB Singapore when to choose rate comparison flexibility penalty' },
            ],
          },
          {
            id: 'lesson-6-3',
            title: 'Building a Cash Ladder',
            icon: '🪜',
            xp: 30,
            duration: '5 min',
            topic: 'cash ladder strategy using HYSAs, SSBs, T-bills and fixed deposits across different time horizons',
            sections: [
              { heading: 'What is a Cash Ladder?', key: 'cash_ladder' },
              { heading: 'Tier 1: Instant Access (HYSA)', key: 'tier1' },
              { heading: 'Tier 2: Short-Term (T-Bills & FDs)', key: 'tier2' },
              { heading: 'Tier 3: Medium-Term (SSBs)', key: 'tier3' },
            ],
            flashcards: [
              { q: 'What is a cash ladder strategy?', ragQuery: 'cash ladder strategy savings liquidity tiers HYSA T-bills SSB time horizon optimise returns' },
              { q: 'What belongs in Tier 1 of a cash ladder?', ragQuery: 'cash ladder tier 1 emergency fund HYSA instant access liquid savings account' },
              { q: 'What belongs in Tier 2 of a cash ladder?', ragQuery: 'cash ladder tier 2 short term T-bills fixed deposit 6 12 months higher rate' },
              { q: 'What belongs in Tier 3 of a cash ladder?', ragQuery: 'cash ladder tier 3 medium term SSB Singapore Savings Bonds 1 to 5 years step up interest' },
              { q: 'How should you divide savings across the three tiers?', ragQuery: 'cash ladder allocation proportion emergency fund short medium term savings rule of thumb' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'module-3',
    title: 'Investing',
    icon: '📈',
    color: '#059669',
    colorLight: '#ECFDF5',
    description: 'Grow your wealth with confidence',
    chapters: [
      {
        id: 'chapter-7',
        title: 'Investing Fundamentals',
        icon: '🎓',
        description: 'Build a solid foundation before picking stocks',
        lessons: [
          {
            id: 'lesson-7-1',
            title: 'Risk, Return & Time',
            icon: '⚖️',
            xp: 40,
            duration: '6 min',
            topic: 'investment risk and return relationship, time horizon importance, volatility, and how young investors can use time to their advantage',
            sections: [
              { heading: 'The Risk-Return Tradeoff', key: 'risk_return' },
              { heading: 'Understanding Volatility', key: 'volatility' },
              { heading: 'Why Time Horizon Changes Everything', key: 'time_horizon' },
              { heading: 'Risk Capacity vs Risk Tolerance', key: 'risk_types' },
            ],
            flashcards: [
              { q: 'What is the risk-return tradeoff?', ragQuery: 'risk return tradeoff investing higher risk higher potential return lower risk lower return Singapore examples' },
              { q: 'What is volatility in investing?', ragQuery: 'volatility investing definition price fluctuation measurement standard deviation investment risk' },
              { q: 'Why does a longer time horizon reduce investment risk?', ragQuery: 'longer time horizon reduces investment risk market recovery long term returns Singapore' },
              { q: 'What is the difference between risk capacity and risk tolerance?', ragQuery: 'risk capacity versus risk tolerance investing afford comfortable financial situation difference' },
              { q: 'What is a risk-adjusted return?', ragQuery: 'risk adjusted return investing Sharpe ratio return per unit risk comparison portfolios' },
            ],
          },
          {
            id: 'lesson-7-2',
            title: 'Asset Classes Explained',
            icon: '🗂️',
            xp: 40,
            duration: '7 min',
            topic: 'asset classes for Singapore investors including equities, bonds, REITs, cash equivalents, and commodities',
            sections: [
              { heading: 'Equities — Ownership in Companies', key: 'equities' },
              { heading: 'Bonds — Lending Money for Interest', key: 'bonds' },
              { heading: 'REITs — Real Estate Without the Mortgage', key: 'reits' },
              { heading: 'Cash & Cash Equivalents', key: 'cash' },
            ],
            flashcards: [
              { q: 'What are equities and how do investors profit from them?', ragQuery: 'equities shares ownership company profit capital appreciation dividends Singapore SGX' },
              { q: 'What are bonds and how do they work?', ragQuery: 'bonds definition lending government company fixed interest coupon maturity lower risk' },
              { q: 'What is a REIT and how does it generate income?', ragQuery: 'REIT real estate investment trust income generating properties distribution yield Singapore' },
              { q: 'Name 3 well-known Singapore REITs', ragQuery: 'Singapore REITs examples CapitaLand Mapletree Ascendas SGX listed prominent' },
              { q: 'How do different asset classes correlate with each other?', ragQuery: 'asset class correlation stocks bonds inverse relationship portfolio diversification volatility reduction' },
            ],
          },
          {
            id: 'lesson-7-3',
            title: 'Diversification & Portfolio Theory',
            icon: '🥧',
            xp: 40,
            duration: '6 min',
            topic: 'diversification in investing, modern portfolio theory, correlation, and building a diversified portfolio',
            sections: [
              { heading: 'Why Diversification Works', key: 'why_diversify' },
              { heading: 'Diversifying Across Asset Classes', key: 'asset_diversify' },
              { heading: 'Geographic Diversification', key: 'geo_diversify' },
              { heading: 'Over-Diversification — When It Hurts', key: 'over_diversify' },
            ],
            flashcards: [
              { q: 'What is diversification and why does it work?', ragQuery: 'diversification investing definition spread risk assets offset losses gains portfolio' },
              { q: 'What is correlation in investing?', ragQuery: 'correlation investing two assets move relative each other low negative better diversification' },
              { q: 'What is systematic vs unsystematic risk?', ragQuery: 'systematic unsystematic risk market wide company specific diversification eliminate reduce' },
              { q: 'How many stocks do you need for effective diversification?', ragQuery: 'number stocks effective diversification research 15 20 uncorrelated ETF instant Singapore' },
              { q: 'What is geographic diversification?', ragQuery: 'geographic diversification investing different countries Singapore US Europe emerging markets reduce risk' },
            ],
          },
        ],
      },
      {
        id: 'chapter-8',
        title: 'Investing in Singapore',
        icon: '🦁',
        description: 'Navigate SGX, REITs, and local investment products',
        lessons: [
          {
            id: 'lesson-8-1',
            title: 'SGX & How It Works',
            icon: '🏛️',
            xp: 40,
            duration: '6 min',
            topic: 'Singapore Exchange SGX trading hours, CDP account, brokerage options, and how to buy your first stock',
            sections: [
              { heading: 'What is SGX?', key: 'sgx' },
              { heading: 'Opening a CDP Account', key: 'cdp' },
              { heading: 'Choosing a Brokerage in Singapore', key: 'brokerage' },
              { heading: 'Placing Your First Trade', key: 'first_trade' },
            ],
            flashcards: [
              { q: 'What is SGX and what are its trading hours?', ragQuery: 'SGX Singapore Exchange stock market trading hours listed companies ETF REIT bonds' },
              { q: 'What is a CDP account and why do you need one?', ragQuery: 'CDP Central Depository account SGX Singapore securities held open free' },
              { q: 'Name 3 brokerages available to Singapore investors', ragQuery: 'Singapore brokerages Tiger Brokers Moomoo Interactive Brokers DBS Vickers OCBC Securities fees' },
              { q: 'What are typical brokerage fees in Singapore?', ragQuery: 'brokerage fees Singapore percentage per trade minimum commission low cost comparison' },
              { q: 'Is there stamp duty on Singapore stock purchases?', ragQuery: 'stamp duty Singapore stock shares purchase transaction tax SGX equities' },
            ],
          },
          {
            id: 'lesson-8-2',
            title: 'STI ETF & Index Investing',
            icon: '📊',
            xp: 40,
            duration: '6 min',
            topic: 'STI ETF index investing, ES3 vs G3B, expense ratios, Regular Savings Plans, and why index investing works',
            sections: [
              { heading: 'What is the STI?', key: 'sti' },
              { heading: 'ES3 vs G3B — The Two STI ETFs', key: 'etfs' },
              { heading: 'Regular Savings Plans for STI ETFs', key: 'rsp' },
              { heading: 'The Case for Index Investing', key: 'case' },
            ],
            flashcards: [
              { q: 'What is the Straits Times Index (STI)?', ragQuery: 'Straits Times Index STI Singapore top 30 companies SGX market capitalisation benchmark' },
              { q: 'What are the two STI ETFs and how do they differ?', ragQuery: 'ES3 G3B STI ETF SPDR Nikko AM Straits Times Index expense ratio difference comparison' },
              { q: 'What is an expense ratio and why does it matter?', ragQuery: 'expense ratio ETF annual fee percentage assets management cost impact returns' },
              { q: 'What is a Regular Savings Plan (RSP) in Singapore?', ragQuery: 'Regular Savings Plan RSP Singapore POSB Invest-Saver OCBC Blue Chip monthly automatic ETF stocks' },
              { q: 'What has been the historical return of the STI?', ragQuery: 'STI historical annual return percentage long term Singapore index performance dividends reinvested' },
            ],
          },
          {
            id: 'lesson-8-3',
            title: 'Singapore REITs Deep Dive',
            icon: '🏢',
            xp: 40,
            duration: '7 min',
            topic: 'Singapore REITs investing, distribution yield, gearing ratio, REIT analysis, and why Singapore is Asia\'s REIT hub',
            sections: [
              { heading: 'Why Singapore is a REIT Hub', key: 'reit_hub' },
              { heading: 'How to Analyse a REIT', key: 'analyse' },
              { heading: 'Popular Singapore REITs', key: 'popular' },
              { heading: 'REITs vs Direct Property', key: 'vs_property' },
            ],
            flashcards: [
              { q: 'Why must Singapore REITs distribute at least 90% of income?', ragQuery: 'Singapore REIT 90 percent distribution requirement tax transparency unitholders income' },
              { q: 'What is distribution yield in REIT investing?', ragQuery: 'REIT distribution yield calculation annual distributions unit price Singapore typical range' },
              { q: 'What is gearing ratio in REITs?', ragQuery: 'REIT gearing ratio debt total assets MAS cap Singapore limit financial risk' },
              { q: 'What is NAV in REIT investing?', ragQuery: 'REIT NAV net asset value per unit assets liabilities units outstanding over under valued' },
              { q: 'What is CapitaLand Integrated Commercial Trust?', ragQuery: 'CapitaLand Integrated Commercial Trust CICT Singapore largest REIT malls offices market cap' },
            ],
          },
        ],
      },
      {
        id: 'chapter-9',
        title: 'Robo-Advisors & DCA',
        icon: '🤖',
        description: 'Invest smarter with automation',
        lessons: [
          {
            id: 'lesson-9-1',
            title: 'Robo-Advisors in Singapore',
            icon: '🤖',
            xp: 40,
            duration: '6 min',
            topic: 'robo-advisors in Singapore including Syfe, StashAway, Endowus comparison and which suits different investor profiles',
            sections: [
              { heading: 'What is a Robo-Advisor?', key: 'what_is_robo' },
              { heading: 'Syfe — Flexible Portfolios', key: 'syfe' },
              { heading: 'StashAway — Risk-Optimised Investing', key: 'stashaway' },
              { heading: 'Endowus — CPF & SRS Specialist', key: 'endowus' },
            ],
            flashcards: [
              { q: 'What is a robo-advisor and how does it work?', ragQuery: 'robo-advisor definition automated investment platform risk profile portfolio rebalance low fees Singapore' },
              { q: 'What are Syfe\'s management fees and portfolio options?', ragQuery: 'Syfe management fee percentage AUM portfolios Core REIT Cash Singapore robo-advisor' },
              { q: 'What is StashAway\'s ERAA investment framework?', ragQuery: 'StashAway ERAA Economic Regime Asset Allocation framework portfolio adjustment Singapore' },
              { q: 'Why is Endowus unique among Singapore robo-advisors?', ragQuery: 'Endowus unique CPF OA SA SRS funds invest robo-advisor Singapore only institutional funds' },
              { q: 'What is a management expense ratio (MER)?', ragQuery: 'management expense ratio MER total annual fund cost robo-advisor fees comparison Singapore' },
            ],
          },
          {
            id: 'lesson-9-2',
            title: 'Dollar-Cost Averaging',
            icon: '📅',
            xp: 40,
            duration: '5 min',
            topic: 'dollar-cost averaging DCA strategy, how it works, why it reduces timing risk, and DCA vs lump sum investing',
            sections: [
              { heading: 'What is Dollar-Cost Averaging?', key: 'what_is_dca' },
              { heading: 'DCA in Practice — A Singapore Example', key: 'example' },
              { heading: 'DCA vs Lump Sum Investing', key: 'vs_lump_sum' },
              { heading: 'Setting Up Automatic DCA in Singapore', key: 'setup' },
            ],
            flashcards: [
              { q: 'What is dollar-cost averaging (DCA)?', ragQuery: 'dollar cost averaging DCA fixed amount regular intervals market price units average cost investing' },
              { q: 'Give a practical DCA example for Singapore investors', ragQuery: 'dollar cost averaging example Singapore STI ETF monthly investment units price lower average cost' },
              { q: 'Does DCA outperform lump sum investing?', ragQuery: 'DCA versus lump sum investing performance comparison historical outperform percentage time' },
              { q: 'How do you set up automatic DCA in Singapore?', ragQuery: 'automatic DCA Singapore POSB Invest-Saver OCBC Blue Chip Syfe StashAway monthly automatic' },
              { q: 'What is the psychological benefit of DCA?', ragQuery: 'psychological benefit dollar cost averaging removes anxiety market timing discipline emotional investing' },
            ],
          },
          {
            id: 'lesson-9-3',
            title: 'Building Your First Portfolio',
            icon: '🏗️',
            xp: 40,
            duration: '7 min',
            topic: 'building a first investment portfolio in Singapore, asset allocation, sample portfolios, and rebalancing',
            sections: [
              { heading: 'Starting with What You Have', key: 'starting' },
              { heading: 'Sample Starter Portfolios', key: 'sample_portfolios' },
              { heading: 'Portfolio Rebalancing', key: 'rebalancing' },
              { heading: 'Your Investment Policy Statement', key: 'ips' },
            ],
            flashcards: [
              { q: 'How much money do you need to start investing in Singapore?', ragQuery: 'minimum amount start investing Singapore robo-advisor RSP ETF SGX low cost beginner' },
              { q: 'What is a simple starter portfolio for a Singapore fresh graduate?', ragQuery: 'simple starter portfolio Singapore fresh graduate 25 years old global equities ETF REIT allocation' },
              { q: 'What is portfolio rebalancing?', ragQuery: 'portfolio rebalancing target allocation drift adjust sell buy restore balance periodically' },
              { q: 'How often should you rebalance your portfolio?', ragQuery: 'portfolio rebalancing frequency annually threshold drift 5 percent transaction costs Singapore' },
              { q: 'What is an Investment Policy Statement (IPS)?', ragQuery: 'Investment Policy Statement IPS personal document goals time horizon risk allocation rebalancing rules' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'module-4',
    title: 'CPF & Advanced Topics',
    icon: '🇸🇬',
    color: '#DC2626',
    colorLight: '#FEF2F2',
    description: 'Master Singapore-specific finance and long-term planning',
    chapters: [
      {
        id: 'chapter-10',
        title: 'CPF Fundamentals',
        icon: '🏛️',
        description: 'Understand Singapore\'s mandatory savings system',
        lessons: [
          {
            id: 'lesson-10-1',
            title: 'CPF Accounts Explained',
            icon: '📋',
            xp: 50,
            duration: '7 min',
            topic: 'CPF accounts OA SA MA RA explained for international graduates working in Singapore',
            sections: [
              { heading: 'The Four CPF Accounts', key: 'four_accounts' },
              { heading: 'CPF Interest Rates', key: 'interest_rates' },
              { heading: 'CPF Contribution Rates', key: 'contribution_rates' },
              { heading: 'How CPF Affects Your Take-Home Pay', key: 'take_home' },
            ],
            flashcards: [
              { q: 'What are the four CPF accounts and their purposes?', ragQuery: 'four CPF accounts Ordinary Special MediSave Retirement Account purpose use Singapore' },
              { q: 'What interest rate does CPF OA earn?', ragQuery: 'CPF Ordinary Account OA interest rate per annum guaranteed additional first 60000' },
              { q: 'What interest rate does CPF SA earn?', ragQuery: 'CPF Special Account SA interest rate per annum guaranteed retirement savings' },
              { q: 'What is the CPF contribution rate for employees under 55?', ragQuery: 'CPF contribution rate employee employer under 55 percentage salary total Singapore' },
              { q: 'Do international graduates on Employment Pass contribute to CPF?', ragQuery: 'international graduates Employment Pass S Pass CPF contribution Singapore permanent resident citizen' },
            ],
          },
          {
            id: 'lesson-10-2',
            title: 'Using CPF Wisely',
            icon: '💡',
            xp: 50,
            duration: '7 min',
            topic: 'using CPF for housing, CPFIS investing, MediShield Life, and maximising CPF for retirement',
            sections: [
              { heading: 'CPF for Housing — OA Utilisation', key: 'housing' },
              { heading: 'CPF Investment Scheme (CPFIS)', key: 'cpfis' },
              { heading: 'MediShield Life & MediSave', key: 'medishield' },
              { heading: 'Should You Invest Your CPF OA?', key: 'invest_oa' },
            ],
            flashcards: [
              { q: 'Can you use CPF OA for HDB purchase?', ragQuery: 'CPF OA Ordinary Account HDB purchase down payment mortgage stamp duty Singapore' },
              { q: 'What is the CPF Investment Scheme (CPFIS)?', ragQuery: 'CPFIS CPF Investment Scheme OA SA minimum balance approved stocks ETF unit trusts invest' },
              { q: 'Why do many people prefer not to invest their CPF OA?', ragQuery: 'CPF OA not invest reason guaranteed 2.5 percent beat CPFIS fees returns comparison' },
              { q: 'What is MediShield Life?', ragQuery: 'MediShield Life mandatory national health insurance Singapore citizens PRs hospital bills MediSave premiums' },
              { q: 'What is the Basic Healthcare Sum (BHS)?', ragQuery: 'Basic Healthcare Sum BHS MediSave cap current amount excess flow SA RA Singapore' },
            ],
          },
          {
            id: 'lesson-10-3',
            title: 'CPF Top-Ups & Tax Relief',
            icon: '💰',
            xp: 50,
            duration: '6 min',
            topic: 'CPF voluntary top-ups, RSTU scheme, SRS, tax relief from CPF contributions',
            sections: [
              { heading: 'Voluntary CPF Top-Ups', key: 'top_ups' },
              { heading: 'Tax Relief from CPF Contributions', key: 'tax_relief' },
              { heading: 'Supplementary Retirement Scheme (SRS)', key: 'srs' },
              { heading: 'Optimising Your Tax Position', key: 'optimise' },
            ],
            flashcards: [
              { q: 'How much tax relief can you get from CPF top-ups?', ragQuery: 'CPF top-up tax relief amount self family members SA RA RSTU Singapore IRAS' },
              { q: 'What is the Retirement Sum Topping-Up Scheme (RSTU)?', ragQuery: 'Retirement Sum Topping-Up Scheme RSTU voluntary cash CPF SA RA tax relief interest rate' },
              { q: 'What is the Supplementary Retirement Scheme (SRS)?', ragQuery: 'SRS Supplementary Retirement Scheme voluntary CPF supplement tax deductible withdrawal retirement' },
              { q: 'What is the SRS contribution limit for Singapore citizens and foreigners?', ragQuery: 'SRS contribution limit Singapore citizens PRs foreigners annual maximum tax deductible' },
              { q: 'What can SRS funds be invested in?', ragQuery: 'SRS funds invest stocks ETF REITs unit trusts fixed deposits insurance MAS approved Endowus' },
            ],
          },
        ],
      },
      {
        id: 'chapter-11',
        title: 'Tax & Insurance',
        icon: '🛡️',
        description: 'Protect what you build and keep more of what you earn',
        lessons: [
          {
            id: 'lesson-11-1',
            title: 'Personal Income Tax in Singapore',
            icon: '🧾',
            xp: 50,
            duration: '7 min',
            topic: 'Singapore personal income tax for fresh graduates, progressive tax rates, filing returns, tax reliefs, and IRAS',
            sections: [
              { heading: 'Singapore\'s Progressive Tax System', key: 'progressive' },
              { heading: 'Tax Reliefs Available to Graduates', key: 'reliefs' },
              { heading: 'Filing Your Tax Return', key: 'filing' },
              { heading: 'Tax Planning for Fresh Grads', key: 'planning' },
            ],
            flashcards: [
              { q: 'What is Singapore\'s personal income tax rate for the first $20,000?', ragQuery: 'Singapore personal income tax rate first 20000 dollars chargeable income zero threshold' },
              { q: 'What are the income tax rates for different income brackets in Singapore?', ragQuery: 'Singapore personal income tax rates brackets progressive 2024 IRAS chargeable income' },
              { q: 'When do you need to file income tax in Singapore?', ragQuery: 'Singapore income tax filing deadline April e-filing paper IRAS first time notification' },
              { q: 'What is the IRAS myTax Portal?', ragQuery: 'IRAS myTax Portal Singapore online tax filing pre-filled employer auto-inclusion scheme' },
              { q: 'Name 3 common tax reliefs for Singapore fresh graduates', ragQuery: 'tax reliefs Singapore fresh graduates CPF Relief Course Fees NSman earned income relief IRAS' },
            ],
          },
          {
            id: 'lesson-11-2',
            title: 'Insurance Essentials',
            icon: '🛡️',
            xp: 50,
            duration: '7 min',
            topic: 'insurance basics for young graduates in Singapore including term vs whole life, Integrated Shield Plans, and coverage amounts',
            sections: [
              { heading: 'Why Insurance Comes Before Investing', key: 'why_insurance' },
              { heading: 'Term vs Whole Life Insurance', key: 'term_vs_whole' },
              { heading: 'Integrated Shield Plans', key: 'shield_plans' },
              { heading: 'How Much Coverage Do You Need?', key: 'how_much' },
            ],
            flashcards: [
              { q: 'Why should you get insurance before investing?', ragQuery: 'insurance before investing protection catastrophic loss medical bills wealth preservation priority' },
              { q: 'What is term life insurance?', ragQuery: 'term life insurance definition fixed period death benefit cheaper whole life recommendation' },
              { q: 'What is whole life insurance?', ragQuery: 'whole life insurance lifetime coverage cash value expensive estate planning Singapore' },
              { q: 'What is an Integrated Shield Plan?', ragQuery: 'Integrated Shield Plan Singapore MediShield Life supplement higher ward private hospital MediSave premiums' },
              { q: 'How much life insurance does a fresh graduate need?', ragQuery: 'life insurance amount fresh graduate Singapore no dependants family support income replacement' },
            ],
          },
          {
            id: 'lesson-11-3',
            title: 'Critical Illness & Disability Coverage',
            icon: '🏥',
            xp: 50,
            duration: '6 min',
            topic: 'critical illness insurance, disability income insurance, TPD coverage, and building an insurance portfolio',
            sections: [
              { heading: 'What is Critical Illness Insurance?', key: 'ci' },
              { heading: 'Disability Income Insurance', key: 'disability' },
              { heading: 'Total Permanent Disability (TPD)', key: 'tpd' },
              { heading: 'Building Your Insurance Portfolio', key: 'portfolio' },
            ],
            flashcards: [
              { q: 'What does critical illness insurance cover?', ragQuery: 'critical illness insurance Singapore lump sum cancer heart attack stroke diagnosis income replacement' },
              { q: 'How much critical illness coverage is recommended?', ragQuery: 'critical illness coverage amount recommended years annual income Singapore guideline' },
              { q: 'What is disability income insurance?', ragQuery: 'disability income insurance monthly replacement cannot work illness injury Singapore young adults' },
              { q: 'What is Total and Permanent Disability (TPD) coverage?', ragQuery: 'Total Permanent Disability TPD coverage lump sum permanently unable work Singapore life insurance' },
              { q: 'What is the correct insurance priority order?', ragQuery: 'insurance priority order Singapore health integrated shield critical illness disability life dependants' },
            ],
          },
        ],
      },
      {
        id: 'chapter-12',
        title: 'Long-Term Financial Planning',
        icon: '🔭',
        description: 'Set yourself up for decades of financial success',
        lessons: [
          {
            id: 'lesson-12-1',
            title: 'Retirement Planning in Your 20s',
            icon: '🌅',
            xp: 50,
            duration: '7 min',
            topic: 'retirement planning for young adults in Singapore, CPF retirement sums, how much you need to retire, and starting early',
            sections: [
              { heading: 'Why Plan for Retirement at 25?', key: 'why_early' },
              { heading: 'CPF Retirement Sums Explained', key: 'retirement_sums' },
              { heading: 'How Much Do You Need to Retire in Singapore?', key: 'how_much' },
              { heading: 'Building Your Retirement Stack', key: 'retirement_stack' },
            ],
            flashcards: [
              { q: 'What are the CPF Retirement Sums?', ragQuery: 'CPF Retirement Sums Basic Full Enhanced BRS FRS ERS amount monthly payout age 65' },
              { q: 'What is CPF LIFE?', ragQuery: 'CPF LIFE Lifelong Income Elderly annuity scheme monthly income retirement account age 65' },
              { q: 'How much do you need to retire comfortably in Singapore?', ragQuery: 'retire comfortably Singapore monthly expenses amount needed retirement sum estimate' },
              { q: 'What is the Rule of 25 for retirement planning?', ragQuery: 'Rule of 25 retirement save 25 times annual expenses 4 percent safe withdrawal rate' },
              { q: 'Why does starting retirement saving at 25 vs 35 matter?', ragQuery: 'starting retirement saving 25 versus 35 years old compound growth difference outcome Singapore' },
            ],
          },
          {
            id: 'lesson-12-2',
            title: 'Cross-Border Money Management',
            icon: '🌏',
            xp: 50,
            duration: '6 min',
            topic: 'cross-border money management for international graduates in Singapore including remittances, Wise, currency risk, and tax implications',
            sections: [
              { heading: 'The International Graduate\'s Money Challenge', key: 'challenge' },
              { heading: 'Remittance Options from Singapore', key: 'remittance' },
              { heading: 'Currency Risk Management', key: 'currency_risk' },
              { heading: 'Tax Implications of Cross-Border Transfers', key: 'tax' },
            ],
            flashcards: [
              { q: 'What is Wise and how does it help with remittances?', ragQuery: 'Wise TransferWise international money transfer Singapore mid-market rate low cost remittance' },
              { q: 'What is the typical bank transfer fee for international remittances from Singapore?', ragQuery: 'Singapore bank international transfer fee flat charge exchange rate spread remittance cost' },
              { q: 'What is currency risk for international graduates?', ragQuery: 'currency risk Singapore dollar exchange rate fluctuation SGD home country remittance timing' },
              { q: 'Are remittances from Singapore taxable in the recipient\'s country?', ragQuery: 'remittances Singapore taxable recipient country personal transfer declaration FEMA rules' },
              { q: 'What is a multi-currency card and who offers one in Singapore?', ragQuery: 'multi-currency card Singapore YouTrip Revolut Wise travel spending foreign currency competitive rate' },
            ],
          },
          {
            id: 'lesson-12-3',
            title: 'Your Financial Plan — Putting It All Together',
            icon: '🗺️',
            xp: 50,
            duration: '8 min',
            topic: 'creating a comprehensive personal financial plan for international graduates in Singapore covering all areas in an integrated framework',
            sections: [
              { heading: 'The Financial Planning Pyramid', key: 'pyramid' },
              { heading: 'Your First 90 Days as a Working Graduate', key: 'first_90' },
              { heading: 'Year 1 Financial Milestones', key: 'year1' },
              { heading: 'Your 5-Year Financial Roadmap', key: 'five_year' },
            ],
            flashcards: [
              { q: 'What is the Financial Planning Pyramid?', ragQuery: 'financial planning pyramid foundation budget emergency fund protection insurance growth investing optimisation tax' },
              { q: 'What are the top 3 financial priorities in your first month of work?', ragQuery: 'first month working Singapore financial priorities HYSA salary emergency fund health insurance' },
              { q: 'What is a net worth statement and why should you track it?', ragQuery: 'net worth statement assets liabilities tracking monthly progress motivation financial planning' },
              { q: 'What should your Year 1 financial milestones be?', ragQuery: 'year 1 financial milestones Singapore fresh graduate emergency fund insurance investment budget' },
              { q: 'What is the ideal savings allocation for a fresh Singapore graduate?', ragQuery: 'ideal savings allocation fresh Singapore graduate emergency fund investments goals lifestyle percentage' },
            ],
          },
        ],
      },
    ],
  },
];

export const getAllLessons = () =>
  MODULES.flatMap(m => m.chapters.flatMap(c => c.lessons));

export const getLessonById = (id) =>
  getAllLessons().find(l => l.id === id);

export const getChapterByLessonId = (lessonId) =>
  MODULES.flatMap(m => m.chapters).find(c => c.lessons.some(l => l.id === lessonId));

export const getModuleByLessonId = (lessonId) =>
  MODULES.find(m => m.chapters.some(c => c.lessons.some(l => l.id === lessonId)));

export const LESSONS = getAllLessons();